spring:
  application:
    name: demo

  # 数据库连接配置
  datasource:
    # 1. 记得把 IP、端口、逻辑库名改成队友给你的
    url: jdbc:mysql://26.122.246.196:3307/sharding_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    # 2. 账号
    username: root
    # 3. 密码
    password: shardingsphere
    driver-class-name: com.mysql.cj.jdbc.Driver

# MyBatis 配置
mybatis:
  configuration:
    # 开启驼峰命名 (user_id -> userId)
    map-underscore-to-camel-case: true

# 日志配置 (帮你打印 SQL，方便调试)
logging:
  level:
    root: info
    # 假设你的 Mapper 包名是 com.example.demo.mapper
    "[com.example.demo.mapper]": debug